default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: andconf_development

test:
  <<: *default
  database: andconf_test

production:
  <<: *default
  database: andconf_production
  username: andconf
  password: <%= ENV['ANDCONF_DATABASE_PASSWORD'] %>
